### ISSUE TITLE
Freeing `atsamv71q21` crate for atsams-rs organization?

### ISSUE THREAD

**Issue by michalfita** [miker1423/atsamv71q21#2]
Hello @miker1423,

We at [atsams-rs](https://github.com/atsams-rs) organization are maintaining PAC crates for all MCUs from SAMx7x families and your unmaintained crate stays in a way to our release plans. Could you, please, consider handing over the crate ownership on [crates.io](https://crates.io/crates/atsamv71q21) to us?

If you're interested in active participation in development of the HAL crate for the whole family you're more than welcome to contribute. We'd be very glad if we don't have apply exception for `atsamv71q21`.

Thank you very much for consideration.

Kind regards,
Michał Fita

**Comment by miker1423** [comment]
Hello Michal,

Sure! Who should add as an owner or how should I hand the crate?
I would really like to contribute, I'll give a check to the repos to see where I can help.

Greetings,
Miguel Pérez García.

**Comment by michalfita** [comment]
Thanks for very prompt response.

Following the `cargo owner` guidelines:
```sh
cargo login
cargo owner --add michalfita
cargo owner --add github:atsams-rs:owners
```
should do the job.

Thanks again.

**Comment by miker1423** [comment]
No problem. 

I'm getting this error when trying to add the group as owner:
```
error: failed to invite owners to crate `atsamv71q21` on registry at https://crates.io

Caused by:
  the remote server responded with an error: could not find the github team atsams-rs/owners
```

**Comment by michalfita** [comment]
Try: `cargo owner --add github:atsams-rs:pac-maintainers`
It seems a team is something I had to create first.

**Comment by miker1423** [comment]
Same problem

**Comment by michalfita** [comment]
OK, leave it for now. I have access, I sort out team access later - not that important ATM.

I'm publishing 0.21.0 now, 66 crates, but I'm throttled by the crates.io.

**Comment by miker1423** [comment]
Hello, should I try again to add the others to the crate or can I close the issue?

**Comment by michalfita** [comment]
@miker1423 I'm closing it now. Thank you very much.
